---
title: "Academic activities"
---

<style>
body {
text-align: justify}
</style>

----

## Peer Review for Journals

* **<a>Insectes Sociaux</a>**

----

## Teaching Experience

* **<a>Behavioural Ecology</a>**  
  Co-instructor with Dr. Nandini Rajamani  
  2020  
  IISER Tirupati

* **<a>Organismal Biology and Evolution</a>**  
  Teaching Assistant for Prof. Sumana Annagiri  
  2018  
  IISER Kolkata

* **<a>Animal Behaviour (Lab)</a>**  
  Teaching Assistant for Prof. Sumana Annagiri  
  2016  
  IISER Kolkata

* **<a>Ecology and Behaviour (Lab)</a>**  
  Teaching Assistant for Prof. Sumana Annagiri and Dr. Anindita Bhadra  
  2016  
  IISER Kolkata

* **<a>Organismal Biology and Evolution</a>**  
  Teaching Assistant for Prof. Sumana Annagiri  
  2015  
  IISER Kolkata

* **<a>Organismal Biology and Evolution</a>**  
  Teaching Assistant for Prof. Sumana Annagiri  
  2014  
  IISER Kolkata

----

## Participation in Events

* <a>**Basics of Working with R** workshop</a>  
  Co-conducted with Dr. Manabi Paul & Dr. Rubina Mondal  
  2019  
  Understanding Behaviour, IISER Kolkata

* <a>**Understanding Behaviour** conference</a>  
  Member of the Organizing Committee  
  2019  
  IISER Kolkata

* <a>**Ambassadors of Evolution** workshop</a>  
  <a>ESEB (European Society for Evolutionary Biology) Outreach Initiative</a>   
  Student Volunteer  
  2017  
  IISER Kolkata

----

## Conference Presentations

* **<a href='https://www.youtube.com/watch?v=46J04wwx_jg' target='_blank'>Modelling palm squirrel distributions with citizen science, social media and traditional data sources</a>**  
  Bishwarup Paul, Senan D'Souza, Swati Udayraj, Aravind P.S. & Nandini Rajamani  
  2020  
  CitSci India

* **<a href='https://www.youtube.com/watch?v=y-OlWCHaDcE' target='_blank'>Investigating break-ins: Intraspecific brood theft in a tropical ant</a>**  
  Bishwarup Paul & Sumana Annagiri  
  2020  
  Animal Behaviour Live: Annual Online Conference 

* **<a href='https://www.youtube.com/watch?v=zT7VRbIiBLs' target='_blank'>Intraspecific brood theft in a tropical ant</a>**  
  Bishwarup Paul & Sumana Annagiri  
  2020  
  57<sup>th</sup> Annual Conference of the Animal Behaviour Society

* **<a href='docs/understanding_behaviour_2019_poster.pdf' target='_blank'>Achieving balance between two tasks at hand: Rescue vs relocation in an ant system</a>**  
  Bishwarup Paul & Sumana Annagiri  
  2019  
  Understanding Behaviour, IISER Kolkata

* **<a href='docs/ECBB_2018_poster.pdf' target='_blank'>Behaviour of brood thieves in an Indian ant</a>**  
  Bishwarup Paul & Sumana Annagiri  
  2018  
  9<sup>th</sup> European Conference on Behavioural Biology (ECBB), Liverpool, United Kingdom.

* **<a href='docs/FIMB_2018_Poster.pdf' target='_blank'>Behaviour of brood thieves in an Indian ant</a>**  
  Bishwarup Paul & Sumana Annagiri  
  2018  
  Frontiers in Modern Biology (FIMB), IISER Kolkata

* **<a href='docs/ANET_2017_talk.pdf' target='_blank'>Mechanism of brood theft in an Indian ant</a>**  
  Bishwarup Paul & Sumana Annagiri  
  2017  
  International Conference in Zoological Sciences and Ants (11<sup>th</sup> ANeT), Punjabi University

* **<a href='docs/YETI_2017_poster.pdf' target='_blank'>Intraspecific brood theft in an Indian queenless ant</a>**  
  Bishwarup Paul & Sumana Annagiri  
  2017  
  Young Ecologists Talk and Interact (YETI), Tezpur University

* **<a href='docs/IBEE_2016_talk.pdf' target='_blank'>Intraspecific brood theft in an Indian queenless ant</a>**  
  Bishwarup Paul, Manabi Paul & Sumana Annagiri  
  2016  
  India-Behaviour, Ecology & Evolution (I-BEE), Corbett National Park

* **<a href='docs/NCEE_2015_poster.pdf' target='_blank'>Robbing thy neighbour: A study in an Indian queenless ant</a>**  
  Bishwarup Paul, Manabi Paul & Sumana Annagiri   
  2015  
  Frontiers in Modern Biology (FIMB), IISER Kolkata

* **<a  href='docs/NCEE_2015_poster.pdf' target='_blank'>Robbing thy neighbour: A study in an Indian queenless ant</a>**  
  Bishwarup Paul, Manabi Paul & Sumana Annagiri  
  2015  
  National Conference on Ethology and Evolution (NCEE), IISER Mohali

* **<a href='docs/FIMB_2013_poster.pdf' target='_blank'>Stealing the young: A case study in the Indian queenless ant</a>**  
  Bishwarup Paul, Manabi Paul & Sumana Annagiri  
  2013  
  Frontiers in Modern Biology (FIMB), IISER Kolkata

----

## Workshops Attended

* <a>**Application of Geoinformatics in Ecological Studies**</a>  
  60<sup>th</sup> IIRS Outreach Programme 
  2020  
  IIRS, ISRO

* <a>**1<sup>st</sup> DST-SERB School on Chemical Ecology**</a>  
  2017  
  NCBS

* <a>**Speciation and the Web of Life**</a>  
  2016  
  IISER Thiruvanathapuram

* <a>**SERB School in Neuroscience**</a>  
  8<sup>th</sup> Edition (Brain Circuits)  
  2014  
  IISER Pune

----

## Memberships

* <a>**Ethological Society of India (ESI)**</a>  
  Life Member

* <a>**Animal Behaviour Society**</a>  
  2020-2021 Annual Membership

----